// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIj74ZdFF90sPIwotV-a1boNmpjWMHkUg',
    appId: '1:673803336541:web:05e61cf7f5b424375d86b4',
    messagingSenderId: '673803336541',
    projectId: 'office-syndrome-65672',
    authDomain: 'office-syndrome-65672.firebaseapp.com',
    storageBucket: 'office-syndrome-65672.appspot.com',
    measurementId: 'G-VNPLHNEZPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATNOJsvYDV2RPXDjvvzcphKwqMaOW1h_Y',
    appId: '1:673803336541:android:9e09153d6a7a2e645d86b4',
    messagingSenderId: '673803336541',
    projectId: 'office-syndrome-65672',
    storageBucket: 'office-syndrome-65672.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn2c5emcD8oGJsHXdVpnX7xmFjQBbZ9zA',
    appId: '1:673803336541:ios:5e67eababda639795d86b4',
    messagingSenderId: '673803336541',
    projectId: 'office-syndrome-65672',
    storageBucket: 'office-syndrome-65672.appspot.com',
    iosBundleId: 'com.example.officeSyndromeV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn2c5emcD8oGJsHXdVpnX7xmFjQBbZ9zA',
    appId: '1:673803336541:ios:1d84adebd0ccfd455d86b4',
    messagingSenderId: '673803336541',
    projectId: 'office-syndrome-65672',
    storageBucket: 'office-syndrome-65672.appspot.com',
    iosBundleId: 'com.example.officeSyndromeV2.RunnerTests',
  );
}
